//! Build registry of optional long-form explanations from `docs/errors/*.md`.
//!
//! **Do not** maintain a parallel list of codes here. Which codes *must* have
//! docs is owned by [`arandu_diagnostics::DiagCode`] and enforced by:
//!
//! ```text
//! cargo run -p xtask -- check-diag-docs
//! ```
//!
//! This script only embeds markdown files that already exist on disk.

use std::env;
use std::fs;
use std::path::Path;

#[allow(clippy::collapsible_if, clippy::unwrap_used, clippy::expect_used)]
fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let docs_dir = Path::new(&manifest_dir).join("../../docs/errors");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest_path = Path::new(&out_dir).join("registry_gen.rs");

    println!("cargo:rerun-if-changed={}", docs_dir.display());

    let mut existing_docs = Vec::new();
    if docs_dir.exists() {
        if let Ok(entries) = fs::read_dir(&docs_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_file() && path.extension().is_some_and(|ext| ext == "md") {
                    if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                        existing_docs.push(stem.to_string());
                    }
                }
            }
        }
    }
    existing_docs.sort();

    // Legacy env: prefer xtask; keep soft message if someone still sets it.
    if env::var("ARANDU_VALIDATE_DOCS").is_ok() {
        println!(
            "cargo:warning=ARANDU_VALIDATE_DOCS is deprecated; use `cargo run -p xtask -- check-diag-docs`"
        );
    }

    let mut arms = String::new();
    for doc in &existing_docs {
        arms.push_str(&format!(
            "        \"{doc}\" => Some(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../docs/errors/{doc}.md\"))),\n",
        ));
    }

    let code = format!(
        "// Generated by build.rs. Do not edit manually.\n\n\
        pub fn get_explanation(code: &str) -> Option<&'static str> {{\n\
        \tmatch code {{\n\
        {arms}\
        \t\t_ => None,\n\
        \t}}\n\
        }}\n"
    );

    fs::write(&dest_path, code).expect("write registry_gen.rs");
}
