use std::env;
use std::fs;
use std::path::Path;

const CODES: &[&str] = &[
    "LX001", "LX002", "LX003", "P001", "P002", "P003", "P004", "P005", "P006", "M001", "M002",
    "M003", "N001", "N002", "N003", "N004", "N005", "N007", "N010", "N011", "T001", "T002", "T003",
    "T004", "T005", "T006", "T007", "T008", "T009", "T010", "T011", "T012", "T013", "T014", "T015",
    "T016", "T017", "T018", "T021", "T024", "T025", "T026", "T027", "T028", "T029", "T030", "T031",
    "T032", "T033", "T034", "L001", "G001", "G002", "O001", "O002", "O003", "O004", "O005", "O006",
    "O007", "O008", "O009", "O010", "O011", "W001", "W002", "W003", "W004", "W005", "W006", "W007",
    "U001",
];

#[allow(clippy::collapsible_if, clippy::unwrap_used, clippy::expect_used)]
fn main() {
    // CARGO_* env vars are always set when Cargo runs build scripts.
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let docs_dir = Path::new(&manifest_dir).join("../../docs/errors");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest_path = Path::new(&out_dir).join("registry_gen.rs");

    // Tell Cargo to re-run the build script if docs/errors changes
    println!("cargo:rerun-if-changed={}", docs_dir.display());

    let mut existing_docs = Vec::new();
    if docs_dir.exists() {
        if let Ok(entries) = fs::read_dir(&docs_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_file() && path.extension().is_some_and(|ext| ext == "md") {
                    if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                        existing_docs.push(stem.to_string());
                    }
                }
            }
        }
    }

    // Check if strict validation is requested
    let validate_docs = env::var("ARANDU_VALIDATE_DOCS").is_ok();

    if validate_docs {
        // Enforce strict bijection
        // 1. Every existing .md must be a valid code
        for doc in &existing_docs {
            if !CODES.contains(&doc.as_str()) {
                panic!(
                    "Documentation file docs/errors/{}.md does not match any declared diagnostic code",
                    doc
                );
            }
        }
        // 2. Every declared code must have a .md
        for code in CODES {
            if !existing_docs.contains(&code.to_string()) {
                panic!(
                    "Missing documentation file docs/errors/{}.md for declared diagnostic code {}",
                    code, code
                );
            }
        }
    }

    // Generate registry_gen.rs content
    let mut arms = String::new();
    for doc in &existing_docs {
        if CODES.contains(&doc.as_str()) {
            arms.push_str(&format!(
                "        \"{}\" => Some(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../docs/errors/{}.md\"))),\n",
                doc, doc
            ));
        }
    }

    let code = format!(
        "// Generated by build.rs. Do not edit manually.\n\n\
        pub fn get_explanation(code: &str) -> Option<&'static str> {{\n\
        \tmatch code {{\n\
        {}\
        \t\t_ => None,\n\
        \t}}\n\
        }}\n",
        arms
    );

    fs::write(&dest_path, code).expect("write registry_gen.rs");
}
